### ISSUE TITLE
Primary ENI IP

### ISSUE THREAD

**Issue by C45tr0** [lyft/cni-ipvlan-vpc-k8s#15]
It looks like the Primary ENI IP is allocated, but not used as a podIP. 

This would not be an issue on bigger servers with more interfaces and IPs per interface, or even more servers, but starting out small this removes precious resources. 

Is there a reason for this or would it be possible to change this behavior? 

Would be willing to do a PR if this can be done and is a good idea.

**Comment by theatrus** [comment]
This should probably be fixed (allocate interface, locate free). Right now we do not have dramatic wastage in production as we use the `cni-ipvlan-vpc-k8s-tool new-interface` invocation at cloud-init to allocate a secondary adapter, however subsequent adapters will still be leak one address on the first pass.

**Comment by theatrus** [comment]
Merged in #17 to fix this.
