### ISSUE TITLE
Dependency on some private lyft repos

### ISSUE THREAD

**Issue by lilida** [lyft/cni-ipvlan-vpc-k8s#2]
Hi, 

I am getting the following errors when trying to retrieve dependencies. Looks like it has some dependencies to private repo:

➜  cni-ipvlan-vpc-k8s git:(master) dep ensure
ensure Solve(): no valid source could be created:
	failed to set up sources from the following URLs:
https://github.com/lyft/cni-eni
: remote repository at https://github.com/lyft/cni-eni does not exist, or is inaccessible: : exit status 128
	failed to set up sources from the following URLs:
ssh://git@github.com/lyft/cni-eni
: remote repository at ssh://git@github.com/lyft/cni-eni does not exist, or is inaccessible: : exit status 128
	failed to set up sources from the following URLs:
git://github.com/lyft/cni-eni
: remote repository at git://github.com/lyft/cni-eni does not exist, or is inaccessible: : exit status 128
	failed to set up sources from the following URLs:
http://github.com/lyft/cni-eni
: remote repository at http://github.com/lyft/cni-eni does not exist, or is inaccessible: : exit status 128

**Comment by theatrus** [comment]
Apologies - fixing this up :)

**Comment by theatrus** [comment]
Should be fixed in #3
