### ISSUE TITLE
Build binaries for 0.5.0 release

### ISSUE THREAD

**Issue by maruina** [lyft/cni-ipvlan-vpc-k8s#73]
Hi all,
I see that we don't have the binaries for the `0.5.0` release, but just the source code. Do you think you would be able to build and publish them as part of the release process, as you did for the `0.4.2` release?

There are some tools like [kops](https://github.com/kubernetes/kops/pull/7402) that are expecting to download the binaries from Github.

**Comment by theatrus** [comment]
https://github.com/lyft/cni-ipvlan-vpc-k8s/releases/tag/v0.5.1

Updated for 0.5.1 - Sorry about the delay!
