### ISSUE TITLE
IP Batching changes the default behavior

### ISSUE THREAD

**Issue by lbernail** [lyft/cni-ipvlan-vpc-k8s#77]
Hello,

I've been working on a PR (coming very soon) and I was surprised at the amount of addresses allocated to the interfaces on my test instance. I discovered it was related to #65 which by will now allocate all possible IPs when an interface is attached by default.

In our setup we have low pod density on nodes and on large instance this will allocate far too many IPs. We can of course configure ipBatchSize, but I think changing the default batch size to 1 would avoid impacting existing setups. More than happy to do this very simple PR if you think it makes sense.

cc @theatrus @jonathanburns

**Comment by theatrus** [comment]
More than happy to do a quick PR to make this default 1. Thanks :)
