### ISSUE TITLE
Binary Release for 0.6.1

### ISSUE THREAD

**Issue by gjtempleton** [lyft/cni-ipvlan-vpc-k8s#82]
Hey there, 
great to see the nice fix in #80 making it into `0.6.1` however I was hoping to update `kubernetes/kops` to use the new version, however that relies on downloading the release binary rather than source code ( see here: https://github.com/kubernetes/kops/blob/8df55b8571c1cd6dc5e6f7fba56175bf0945fb74/upup/pkg/fi/cloudup/apply_cluster.go#L1183 )

As such it would be great if you could publish the binary of the `0.6.1` release.

Thanks!

**Comment by theatrus** [comment]
Thanks for the note - my oversight. Will get this fixed up

**Comment by gjtempleton** [comment]
No worries, and thanks for all your work on this!

**Comment by gjtempleton** [comment]
Closing this as there's binaries for 0.6.3 and that's good enough for us, thanks!
